version: '3.8'

services:
  db:
    image: postgres
    container_name: webshop
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"